##Information security control

###Passwords control
1.	Asignate secure passwords generated by a password generating tool.
2.	Manage passwords using a password manager software.
3.	Change passwords monthly or quarterly.
4.	Each user would have different password.
5.	Passwords would be sent through VPN encrypted connection, never sent by e-mail.

###Phishing prevention
1.	Implement a wordpress anti-phishing plugin.
A plugin can be used is dmarcian, which allow view the mails received status (about possible phishing attacks).
![image]()

###DDoS prevention
1.	Implement a wordpress anti-DDoS plugin.
For prevent issues caused by a DDoS (Distributed Denial of Service) attacks could to use Protection Against DDoS wordpress plugin, which addresses that issues.


###Spam prevention
1.	Implement a wordpress anti-spam plugin.
Akismet checks your contact form submissions against a global database of spam to prevent the website from getting malicious content.


###SSL Certification
Is very important to have SSL certification on the website for keep data secure and give security to the clients, because SSL provides a secure connection between the server and the clients.
To install a SSL certification in the website we need:
*	A SSL certification (key)
*	Configure the SSL certification in Wordpress.
A SSL certification can be generated through MMC tools from Wiindows Server operating system.
To activate the SSL certification in the website, the easiest way yo do it is using a SSL configuration wordpress plugin called Really Simple SSL, or set up manually on the Wordpress configuration panel instead.
